twig:
    default_path: "%kernel.project_dir%/templates"
    form_themes: ["bootstrap_4_layout.html.twig"]

    paths:
        "%kernel.project_dir%/public/images/email": images
        '%kernel.project_dir%/assets/styles/emails': styles
